name: 'Auto Run'

run-name: '0.0.${{ github.event.workflow_run.run_number}} - ${{ github.workflow }}'

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - main

concurrency:
  group: tests
  cancel-in-progress: true

jobs:
  docker_run:
    strategy:
      matrix:
        env: ['dev', 'uat', 'prod']
    uses: mars-office/.github/.github/workflows/docker-run.yaml@main
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    secrets: inherit
    with:
      version: 'v0.0.${{ github.event.workflow_run.run_number }}'
      env: ${{ matrix.env }}
      imageName: 'huna-automation'
